### ISSUE TITLE
Simple Example fails

### ISSUE THREAD

**Issue by Krutsch** [danielroe/beasties#11]
The Example in readme:

```js
import Beasties from "beasties";

const beasties = new Beasties({
  // optional configuration (see below)
});

const html = `
  <style>
    .red { color: red }
    .blue { color: blue }
  </style>
  <div class="blue">I'm Blue</div>
`;

const inlined = await beasties.process(html);

console.log(inlined);
// "<style>.blue{color:blue}</style><div class=\"blue\">I'm Blue</div>"
````

fails with this message:

```bash
file:///C:/Users/.../node_modules/beasties/dist/beasties.mjs:477
    document.documentElement.setAttribute('data-beasties-container', '');
                             ^

TypeError: Cannot read properties of undefined (reading 'setAttribute')
    at createDocument (file:///C:/Users/.../node_modules/beasties/dist/beasties.mjs:477:30)
    at Beasties.process (file:///C:/Users/.../node_modules/beasties/dist/beasties.mjs:1069:22)
    at file:///C:/Users/.../test.js:15:32
    at ModuleJob.run (node:internal/modules/esm/module_job:268:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:543:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:116:5)
```

Device: Windows 11, Node.js version 23.0.0 but also on v21.6.0

**Comment by danielroe** [comment]
Indeed, the example seems flawed (it is also reproducible for `critters`). You can work around it by providing a root `<html>` element.

I think it should still work if it doesn't exist though.
